#!/usr/bin/env bash
# bash script that transfers a file from our client to a server
# Arguments:
#   - Path to the file to be transferred
#   - IP of the server to transfer the file to
#   - Username that 'scp' connects with
#   - Path to the SSH private key that 'scp' uses to connect

if [ $# -lt 4 ]
then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
  scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
fi
