#!/usr/bin/env bash
# bash script that installs HAProxy & makes configurations to meet the following requirements:
#   - Distribute requests using a roundrobin algorithm
#   - Make sure that HAproxy can be managed via an init script
#   - Make sure that your servers are configured with the right hostnames: [STUDENT_ID]-web-01, [STUDENT_ID]-web-02

apt-get -y install software-properties-common
add-apt-repository ppa:vbernat/haproxy-1.8
apt-get update
apt-get -y install haproxy
echo "ENABLED=1" >> /etc/default/haproxy
printf %s "listen 185927-webs
    bind *:80
    mode http
    balance roundrobin
    server 185927-web-01 100.25.36.224:80 check
    server 185927-web-02  54.90.15.94:80 check
" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
