#!/usr/bin/env bash
# bash script that pings an IP adress as an argument 5 times

#!/usr/bin/env bash
# Script that pings an IP address received as an argument 5 times.

if [ $# -eq 0 ]
then
  echo "Usage: $(basename "$0") {IP_ADDRESS}"
else
  ping -c 5 "$1"
fi
