#!/usr/bin/env bash
# bash script that configures 'nginx' to run & listen to port 80
sudo apt update && sudo apt upgrade && sudo apt install nginx
service nginx start
sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
service nginx restart
