#!/usr/bin/env bash
# Bash script that displays the visitor IP along with the HTTP status code from the Apache log file
# Format: IP HTTP_CODE
# List format
# Use 'awk'

awk '{print $1 " " $9}' apache-access.log
