#!/usr/bin/env bash
# Bash script that displays 'Best School' ten times, but for the ninth iteration, displays 'Best School' & then 'Hi' on a new line
# Use while loop & if statement only

count=0

while [ $count -lt 10 ]
do
  if [ $count -eq 9 ]
  then
    echo "Hi"
  fi
  echo "Best School"
  (( count++ ))
done
