#!/usr/bin/env bash
# bash script to reload gunicorn in a graceful way.

master_pid=$(pgrep -f gunicorn) && kill -HUP "$master_pid" && wait "$master_pid" && gunicorn --bind 0.0.0.0:8001 --workers 4 web_flask.0-hello_route:app
